In [1]:
#import libraries
import pandas as pd
import numpy as np
import os
import pickle

In [2]:
df_ords_prods_merged=pd.read_pickle(os.path.join(r'C:\Users\jadep\Documents\Career Foundry\Achievement 4\04-2020Instacart Basket Analysis\Data\Prepared Data\ords_prods_merged.pkl'))

In [6]:
#create 'max order'
df_ords_prods_merged['max_order'] = df_ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [8]:
df_ords_prods_merged.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,time_order_placed,days_since_prior_order,product_id,add_to_cart_order,...,department_id,prices,exists,price_range_loc,busiest day,busiest days,Busiest_period_of_day,busiest_period_of_day,busiest,max_order
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,most orders,average orders,average,10
1,1,2398795,1,prior,2,3,7,15.0,196,1,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,most orders,average orders,average,10
2,2,473747,1,prior,3,3,12,21.0,196,1,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,most orders,Most orders,average,10
3,3,2254736,1,prior,4,4,7,29.0,196,1,...,7,9.0,both,Mid-range product,Least busy,Least busy days,most orders,average orders,average,10
4,4,431534,1,prior,5,4,15,28.0,196,1,...,7,9.0,both,Mid-range product,Least busy,Least busy days,most orders,Most orders,average,10

In [10]:
#create 'loyalty flag'
df_ords_prods_merged.loc[df_ords_prods_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df_ords_prods_merged.loc[(df_ords_prods_merged['max_order'] <= 40) & (df_ords_prods_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df_ords_prods_merged.loc[df_ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [13]:
#check for 'loyalty flag'
df_ords_prods_merged.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,time_order_placed,days_since_prior_order,product_id,add_to_cart_order,...,prices,exists,price_range_loc,busiest day,busiest days,Busiest_period_of_day,busiest_period_of_day,busiest,max_order,loyalty_flag
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,most orders,average orders,average,10,New customer
1,1,2398795,1,prior,2,3,7,15.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy days,most orders,average orders,average,10,New customer
2,2,473747,1,prior,3,3,12,21.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy days,most orders,Most orders,average,10,New customer
3,3,2254736,1,prior,4,4,7,29.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy days,most orders,average orders,average,10,New customer
4,4,431534,1,prior,5,4,15,28.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy days,most orders,Most orders,average,10,New customer

In [15]:
#average price by customer loyalty
df_ords_prods_merged.groupby('loyalty_flag').agg({'prices':['mean','min','max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

In [16]:
#create 'avg price'
df_ords_prods_merged['avg_price'] = df_ords_prods_merged.groupby(['user_id'])['prices'].transform(np.mean)

In [17]:
df_ords_prods_merged.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,time_order_placed,days_since_prior_order,product_id,add_to_cart_order,...,exists,price_range_loc,busiest day,busiest days,Busiest_period_of_day,busiest_period_of_day,busiest,max_order,loyalty_flag,avg_price
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,both,Mid-range product,Regularly busy,Regularly busy,most orders,average orders,average,10,New customer,6.367797
1,1,2398795,1,prior,2,3,7,15.0,196,1,...,both,Mid-range product,Regularly busy,Least busy days,most orders,average orders,average,10,New customer,6.367797
2,2,473747,1,prior,3,3,12,21.0,196,1,...,both,Mid-range product,Regularly busy,Least busy days,most orders,Most orders,average,10,New customer,6.367797
3,3,2254736,1,prior,4,4,7,29.0,196,1,...,both,Mid-range product,Least busy,Least busy days,most orders,average orders,average,10,New customer,6.367797
4,4,431534,1,prior,5,4,15,28.0,196,1,...,both,Mid-range product,Least busy,Least busy days,most orders,Most orders,average,10,New customer,6.367797

In [18]:
df_ords_prods_merged.loc[df_ords_prods_merged['avg_price'] <10, 'spending_flag'] = 'Low spender'
df_ords_prods_merged.loc[df_ords_prods_merged['avg_price'] >= 10, 'spender_flag'] = 'High spender'

MemoryError: Unable to allocate 2.41 GiB for an array with shape (10, 32404859) and data type object

In [27]:
#limit dataset for memory
df2=df_ords_prods_merged[:10000000]

In [28]:
#create 'spending flag'
df2.loc[df2['avg_price'] <10, 'spending_flag'] = 'Low spender'
df2.loc[df2['avg_price'] >= 10, 'spender_flag'] = 'High spender'

C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [29]:
#check spending flag counts
df2['spending_flag'].value_counts(dropna=False)

Low spender    9867959
NaN             132041
Name: spending_flag, dtype: int64

In [30]:
#create 'order frequency'
df_ords_prods_merged['order_frequency'] = df_ords_prods_merged.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [31]:
df_ords_prods_merged.head()

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_week,time_order_placed,days_since_prior_order,product_id,add_to_cart_order,...,busiest day,busiest days,Busiest_period_of_day,busiest_period_of_day,busiest,max_order,loyalty_flag,avg_price,spending_flag,order_frequency
0,0,2539329,1,prior,1,2,8,NaN,196,1,...,Regularly busy,Regularly busy,most orders,average orders,average,10,New customer,6.367797,Low spender,20.5
1,1,2398795,1,prior,2,3,7,15.0,196,1,...,Regularly busy,Least busy days,most orders,average orders,average,10,New customer,6.367797,Low spender,20.5
2,2,473747,1,prior,3,3,12,21.0,196,1,...,Regularly busy,Least busy days,most orders,Most orders,average,10,New customer,6.367797,Low spender,20.5
3,3,2254736,1,prior,4,4,7,29.0,196,1,...,Least busy,Least busy days,most orders,average orders,average,10,New customer,6.367797,Low spender,20.5
4,4,431534,1,prior,5,4,15,28.0,196,1,...,Least busy,Least busy days,most orders,Most orders,average,10,New customer,6.367797,Low spender,20.5

In [32]:
df_ords_prods_merged.loc[df_ords_prods_merged['order_frequency'] >20, 'frequency_flag'] = 'Non frequent customer'
df_ords_prods_merged.loc[(df_ords_prods_merged['order_frequency'] <= 20) & (df_ords_prods_merged['order_frequency'] > 10), 'frequency_flag'] = 'Regular customer'
df_ords_prods_merged.loc[df_ords_prods_merged['order_frequency'] < 10, 'frequency_flag'] = 'Frequent customer'

MemoryError: Unable to allocate 989. MiB for an array with shape (4, 32404859) and data type float64

In [37]:
#limit dataframe for memory
df2=df_ords_prods_merged[:1000000]

In [38]:
df2.loc[df2['order_frequency'] >20, 'frequency_flag'] = 'Non frequent customer'
df2.loc[(df2['order_frequency'] <= 20) & (df2['order_frequency'] > 10), 'frequency_flag'] = 'Regular customer'
df2.loc[df2['order_frequency'] < 10, 'frequency_flag'] = 'Frequent customer'

C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
C:\Users\jadep\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [39]:
df2['frequency_flag'].value_counts(dropna=False)

Frequent customer        658181
Regular customer         204715
Non frequent customer    100199
NaN                       36905
Name: frequency_flag, dtype: int64

In [45]:
path =r'C:\Users\jadep\Documents\Career Foundry\Achievement 4\04-2020Instacart Basket Analysis'

In [57]:
df_ords_prods_merged.to_csv(os.path.join(path,'Data','Prepared Data','orders_products_merged.csv'))